name: golem-dracor-api
services:
  api:
    build:
      context: .
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
        - dev.env
  triplestore:
    image: "openlink/virtuoso-opensource-7:latest"
    ports:
      - "8890:8890"
    environment:
      - DBA_PASSWORD=pwd123
    expose:
      - "8890"
