name: golem-dracor-api
services:
  api:
    build:
      context: .
    depends_on:
      - triplestore
    links:
      - triplestore
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
        - dev.env
  triplestore:
    image: "openlink/virtuoso-opensource-7:latest"
    ports:
      - "8890:8890"
    environment:
      - DBA_PASSWORD=pwd123
    expose:
      - "8890"
  frontend:
    build:
      context: https://github.com/GOLEM-lab/golem-corpora-frontend.git#main
    environment:
      DRACOR_API: http://api:5000/
    ports:
      - "8088:80"
    depends_on:
      - api