version: '2'
services:
  catch-protagonist:
    image: "poecor/postdata-2-dracor-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
        - dev.env