info:
  description: '

    Middleware to connect POSTDATA to a DraCor-like frontend.'
  contact:
    name: "Ingo B\xF6rner"
    email: ingo.boerner@uni-potsdam.de
  license:
    name: GPL-3.0 license
    url: https://www.gnu.org/licenses/gpl-3.0.html
  title: Poecor POSTDATA connector
  version: '1.0'
servers:
- description: Local Flask
  url: http://localhost:5000
- description: Production
  url: https://poecor.org/api
- description: Staging
  url: https://staging.poecor.org/api
externalDocs:
  description: Code on Github
  url: https://github.com/dh-network/postdata-2-dracor-api
paths:
  /info:
    get:
      summary: About the service
      description: Returns information about the service's API
      operationId: get_info
      responses:
        '200':
          description: Information about the API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoResponse'
  /corpora:
    get:
      summary: List available corpora
      description: Returns a list of available corpora
      operationId: get_corpora
      parameters:
      - in: query
        name: include
        description: Include additional information, e.g. corpus metrics.
        required: false
        example: metrics
        schema:
          type: string
          enum:
          - metrics
      responses:
        '200':
          description: Available corpora.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CorpusMetadata'
        '400':
          description: Invalid value of parameter "include".
          content:
            text/plain:
              schema:
                type: string
openapi: 3.0.3
components:
  schemas:
    InfoResponse:
      type: object
      properties:
        description:
          type: string
        version:
          type: string
        name:
          type: string
    CorpusMetrics:
      type: object
      properties:
        metrical_syllables:
          type: integer
        verses:
          type: integer
        authors:
          type: integer
        words:
          type: integer
        grammatical_syllables:
          type: integer
        stanzas:
          type: integer
        poems:
          type: integer
    CorpusMetadata:
      type: object
      properties:
        title:
          type: string
        metrics:
          $ref: '#/components/schemas/CorpusMetrics'
        description:
          type: string
        name:
          type: string
